---
- name: Create systemd unit for Unicorn
  template:
    src: unicorn.service.j2
    dest: /etc/systemd/system/donalo.service
    mode: 0644

- include_role:
    name: vendor/coopdevs.certbot_nginx
  vars:
    domain_name: "{{ inventory_hostname }}"
    letsencrypt_email: "{{ certificate_authority_email }}"

- include_role:
    name: vendor/jdauphant.nginx
  vars:
    nginx_configs:
      upstream:
        - upstream app_server { server unix:{{ unicorn_socket }} fail_timeout=0; }
    nginx_sites:
      donalo_https:
        template: donalo_https.conf.j2
        server_name: "{{ inventory_hostname }}"
      donalo_http:
        template: donalo_http.conf.j2
        server_name: "{{ inventory_hostname }}"
